/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreatePasswordRouteImport } from './routes/create-password'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as LockRouteImport } from './routes/lock'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StaffLoginRouteImport } from './routes/staff-login'
import { Route as TrackRouteImport } from './routes/track'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalInvoicesRouteImport } from './routes/portal.invoices'
import { Route as PortalNotificationsRouteImport } from './routes/portal.notifications'
import { Route as PortalPaymentsRouteImport } from './routes/portal.payments'
import { Route as PortalPickupsRouteImport } from './routes/portal.pickups'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as PortalShipmentsRouteImport } from './routes/portal.shipments'
import { Route as PortalSupportRouteImport } from './routes/portal.support'
import { Route as PortalTrackingRouteImport } from './routes/portal.tracking'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffAuditLogsRouteImport } from './routes/staff.audit-logs'
import { Route as StaffCompanyRouteImport } from './routes/staff.company'
import { Route as StaffCustomersRouteImport } from './routes/staff.customers'
import { Route as StaffDocumentsRouteImport } from './routes/staff.documents'
import { Route as StaffDriverPaymentsRouteImport } from './routes/staff.driver-payments'
import { Route as StaffDriversRouteImport } from './routes/staff.drivers'
import { Route as StaffFinanceRouteImport } from './routes/staff.finance'
import { Route as StaffFleetRouteImport } from './routes/staff.fleet'
import { Route as StaffFuelRouteImport } from './routes/staff.fuel'
import { Route as StaffMaintenanceRouteImport } from './routes/staff.maintenance'
import { Route as StaffNotificationsRouteImport } from './routes/staff.notifications'
import { Route as StaffReportsRouteImport } from './routes/staff.reports'
import { Route as StaffSalariesRouteImport } from './routes/staff.salaries'
import { Route as StaffSettingsRouteImport } from './routes/staff.settings'
import { Route as StaffShipmentsRouteImport } from './routes/staff.shipments'
import { Route as StaffTransportOrdersRouteImport } from './routes/staff.transport-orders'
import { Route as StaffTripsRouteImport } from './routes/staff.trips'
import { Route as StaffUsersRouteImport } from './routes/staff.users'
import { Route as StaffVehicleProfitRouteImport } from './routes/staff.vehicle-profit'
import { Route as StaffWarehousesRouteImport } from './routes/staff.warehouses'
import { Route as StaffDriversDriverIdRouteImport } from './routes/staff.drivers.$driverId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePasswordRoute = CreatePasswordRouteImport.update({
  id: '/create-password',
  path: '/create-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInvoicesRoute = PortalInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNotificationsRoute = PortalNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPaymentsRoute = PortalPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPickupsRoute = PortalPickupsRouteImport.update({
  id: '/pickups',
  path: '/pickups',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalShipmentsRoute = PortalShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSupportRoute = PortalSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTrackingRoute = PortalTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => PortalRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAuditLogsRoute = StaffAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCompanyRoute = StaffCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCustomersRoute = StaffCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDocumentsRoute = StaffDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDriverPaymentsRoute = StaffDriverPaymentsRouteImport.update({
  id: '/driver-payments',
  path: '/driver-payments',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDriversRoute = StaffDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFinanceRoute = StaffFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFleetRoute = StaffFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFuelRoute = StaffFuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMaintenanceRoute = StaffMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => StaffRoute,
} as any)
const StaffNotificationsRoute = StaffNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StaffRoute,
} as any)
const StaffReportsRoute = StaffReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => StaffRoute,
} as any)
const StaffSalariesRoute = StaffSalariesRouteImport.update({
  id: '/salaries',
  path: '/salaries',
  getParentRoute: () => StaffRoute,
} as any)
const StaffSettingsRoute = StaffSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StaffRoute,
} as any)
const StaffShipmentsRoute = StaffShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => StaffRoute,
} as any)
const StaffTransportOrdersRoute = StaffTransportOrdersRouteImport.update({
  id: '/transport-orders',
  path: '/transport-orders',
  getParentRoute: () => StaffRoute,
} as any)
const StaffTripsRoute = StaffTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => StaffRoute,
} as any)
const StaffUsersRoute = StaffUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => StaffRoute,
} as any)
const StaffVehicleProfitRoute = StaffVehicleProfitRouteImport.update({
  id: '/vehicle-profit',
  path: '/vehicle-profit',
  getParentRoute: () => StaffRoute,
} as any)
const StaffWarehousesRoute = StaffWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDriversDriverIdRoute = StaffDriversDriverIdRouteImport.update({
  id: '/$driverId',
  path: '/$driverId',
  getParentRoute: () => StaffDriversRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/create-password': typeof CreatePasswordRoute
  '/driver': typeof DriverRouteWithChildren
  '/fleet': typeof FleetRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/lock': typeof LockRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/news': typeof NewsRoute
  '/otp': typeof OtpRoute
  '/portal': typeof PortalRouteWithChildren
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/staff': typeof StaffRouteWithChildren
  '/staff-login': typeof StaffLoginRoute
  '/track': typeof TrackRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/pickups': typeof PortalPickupsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/shipments': typeof PortalShipmentsRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/tracking': typeof PortalTrackingRoute
  '/staff/audit-logs': typeof StaffAuditLogsRoute
  '/staff/company': typeof StaffCompanyRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/documents': typeof StaffDocumentsRoute
  '/staff/driver-payments': typeof StaffDriverPaymentsRoute
  '/staff/drivers': typeof StaffDriversRouteWithChildren
  '/staff/finance': typeof StaffFinanceRoute
  '/staff/fleet': typeof StaffFleetRoute
  '/staff/fuel': typeof StaffFuelRoute
  '/staff/maintenance': typeof StaffMaintenanceRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/salaries': typeof StaffSalariesRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/shipments': typeof StaffShipmentsRoute
  '/staff/transport-orders': typeof StaffTransportOrdersRoute
  '/staff/trips': typeof StaffTripsRoute
  '/staff/users': typeof StaffUsersRoute
  '/staff/vehicle-profit': typeof StaffVehicleProfitRoute
  '/staff/warehouses': typeof StaffWarehousesRoute
  '/driver/': typeof DriverIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/drivers/$driverId': typeof StaffDriversDriverIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/create-password': typeof CreatePasswordRoute
  '/fleet': typeof FleetRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/lock': typeof LockRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/news': typeof NewsRoute
  '/otp': typeof OtpRoute
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/staff-login': typeof StaffLoginRoute
  '/track': typeof TrackRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/pickups': typeof PortalPickupsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/shipments': typeof PortalShipmentsRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/tracking': typeof PortalTrackingRoute
  '/staff/audit-logs': typeof StaffAuditLogsRoute
  '/staff/company': typeof StaffCompanyRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/documents': typeof StaffDocumentsRoute
  '/staff/driver-payments': typeof StaffDriverPaymentsRoute
  '/staff/drivers': typeof StaffDriversRouteWithChildren
  '/staff/finance': typeof StaffFinanceRoute
  '/staff/fleet': typeof StaffFleetRoute
  '/staff/fuel': typeof StaffFuelRoute
  '/staff/maintenance': typeof StaffMaintenanceRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/salaries': typeof StaffSalariesRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/shipments': typeof StaffShipmentsRoute
  '/staff/transport-orders': typeof StaffTransportOrdersRoute
  '/staff/trips': typeof StaffTripsRoute
  '/staff/users': typeof StaffUsersRoute
  '/staff/vehicle-profit': typeof StaffVehicleProfitRoute
  '/staff/warehouses': typeof StaffWarehousesRoute
  '/driver': typeof DriverIndexRoute
  '/portal': typeof PortalIndexRoute
  '/staff': typeof StaffIndexRoute
  '/staff/drivers/$driverId': typeof StaffDriversDriverIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/create-password': typeof CreatePasswordRoute
  '/driver': typeof DriverRouteWithChildren
  '/fleet': typeof FleetRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/lock': typeof LockRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/news': typeof NewsRoute
  '/otp': typeof OtpRoute
  '/portal': typeof PortalRouteWithChildren
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/staff': typeof StaffRouteWithChildren
  '/staff-login': typeof StaffLoginRoute
  '/track': typeof TrackRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/pickups': typeof PortalPickupsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/shipments': typeof PortalShipmentsRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/tracking': typeof PortalTrackingRoute
  '/staff/audit-logs': typeof StaffAuditLogsRoute
  '/staff/company': typeof StaffCompanyRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/documents': typeof StaffDocumentsRoute
  '/staff/driver-payments': typeof StaffDriverPaymentsRoute
  '/staff/drivers': typeof StaffDriversRouteWithChildren
  '/staff/finance': typeof StaffFinanceRoute
  '/staff/fleet': typeof StaffFleetRoute
  '/staff/fuel': typeof StaffFuelRoute
  '/staff/maintenance': typeof StaffMaintenanceRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/salaries': typeof StaffSalariesRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/shipments': typeof StaffShipmentsRoute
  '/staff/transport-orders': typeof StaffTransportOrdersRoute
  '/staff/trips': typeof StaffTripsRoute
  '/staff/users': typeof StaffUsersRoute
  '/staff/vehicle-profit': typeof StaffVehicleProfitRoute
  '/staff/warehouses': typeof StaffWarehousesRoute
  '/driver/': typeof DriverIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/drivers/$driverId': typeof StaffDriversDriverIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/branches'
    | '/careers'
    | '/contact'
    | '/create-password'
    | '/driver'
    | '/fleet'
    | '/forgot-password'
    | '/industries'
    | '/lock'
    | '/login'
    | '/maintenance'
    | '/news'
    | '/otp'
    | '/portal'
    | '/quote'
    | '/reset-password'
    | '/services'
    | '/staff'
    | '/staff-login'
    | '/track'
    | '/unauthorized'
    | '/portal/invoices'
    | '/portal/notifications'
    | '/portal/payments'
    | '/portal/pickups'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/shipments'
    | '/portal/support'
    | '/portal/tracking'
    | '/staff/audit-logs'
    | '/staff/company'
    | '/staff/customers'
    | '/staff/documents'
    | '/staff/driver-payments'
    | '/staff/drivers'
    | '/staff/finance'
    | '/staff/fleet'
    | '/staff/fuel'
    | '/staff/maintenance'
    | '/staff/notifications'
    | '/staff/reports'
    | '/staff/salaries'
    | '/staff/settings'
    | '/staff/shipments'
    | '/staff/transport-orders'
    | '/staff/trips'
    | '/staff/users'
    | '/staff/vehicle-profit'
    | '/staff/warehouses'
    | '/driver/'
    | '/portal/'
    | '/staff/'
    | '/staff/drivers/$driverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/branches'
    | '/careers'
    | '/contact'
    | '/create-password'
    | '/fleet'
    | '/forgot-password'
    | '/industries'
    | '/lock'
    | '/login'
    | '/maintenance'
    | '/news'
    | '/otp'
    | '/quote'
    | '/reset-password'
    | '/services'
    | '/staff-login'
    | '/track'
    | '/unauthorized'
    | '/portal/invoices'
    | '/portal/notifications'
    | '/portal/payments'
    | '/portal/pickups'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/shipments'
    | '/portal/support'
    | '/portal/tracking'
    | '/staff/audit-logs'
    | '/staff/company'
    | '/staff/customers'
    | '/staff/documents'
    | '/staff/driver-payments'
    | '/staff/drivers'
    | '/staff/finance'
    | '/staff/fleet'
    | '/staff/fuel'
    | '/staff/maintenance'
    | '/staff/notifications'
    | '/staff/reports'
    | '/staff/salaries'
    | '/staff/settings'
    | '/staff/shipments'
    | '/staff/transport-orders'
    | '/staff/trips'
    | '/staff/users'
    | '/staff/vehicle-profit'
    | '/staff/warehouses'
    | '/driver'
    | '/portal'
    | '/staff'
    | '/staff/drivers/$driverId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/branches'
    | '/careers'
    | '/contact'
    | '/create-password'
    | '/driver'
    | '/fleet'
    | '/forgot-password'
    | '/industries'
    | '/lock'
    | '/login'
    | '/maintenance'
    | '/news'
    | '/otp'
    | '/portal'
    | '/quote'
    | '/reset-password'
    | '/services'
    | '/staff'
    | '/staff-login'
    | '/track'
    | '/unauthorized'
    | '/portal/invoices'
    | '/portal/notifications'
    | '/portal/payments'
    | '/portal/pickups'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/shipments'
    | '/portal/support'
    | '/portal/tracking'
    | '/staff/audit-logs'
    | '/staff/company'
    | '/staff/customers'
    | '/staff/documents'
    | '/staff/driver-payments'
    | '/staff/drivers'
    | '/staff/finance'
    | '/staff/fleet'
    | '/staff/fuel'
    | '/staff/maintenance'
    | '/staff/notifications'
    | '/staff/reports'
    | '/staff/salaries'
    | '/staff/settings'
    | '/staff/shipments'
    | '/staff/transport-orders'
    | '/staff/trips'
    | '/staff/users'
    | '/staff/vehicle-profit'
    | '/staff/warehouses'
    | '/driver/'
    | '/portal/'
    | '/staff/'
    | '/staff/drivers/$driverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BranchesRoute: typeof BranchesRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CreatePasswordRoute: typeof CreatePasswordRoute
  DriverRoute: typeof DriverRouteWithChildren
  FleetRoute: typeof FleetRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IndustriesRoute: typeof IndustriesRoute
  LockRoute: typeof LockRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  NewsRoute: typeof NewsRoute
  OtpRoute: typeof OtpRoute
  PortalRoute: typeof PortalRouteWithChildren
  QuoteRoute: typeof QuoteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  StaffRoute: typeof StaffRouteWithChildren
  StaffLoginRoute: typeof StaffLoginRoute
  TrackRoute: typeof TrackRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-password': {
      id: '/create-password'
      path: '/create-password'
      fullPath: '/create-password'
      preLoaderRoute: typeof CreatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lock': {
      id: '/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof LockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-login': {
      id: '/staff-login'
      path: '/staff-login'
      fullPath: '/staff-login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/invoices': {
      id: '/portal/invoices'
      path: '/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof PortalInvoicesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/notifications': {
      id: '/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalNotificationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/payments': {
      id: '/portal/payments'
      path: '/payments'
      fullPath: '/portal/payments'
      preLoaderRoute: typeof PortalPaymentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/pickups': {
      id: '/portal/pickups'
      path: '/pickups'
      fullPath: '/portal/pickups'
      preLoaderRoute: typeof PortalPickupsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/shipments': {
      id: '/portal/shipments'
      path: '/shipments'
      fullPath: '/portal/shipments'
      preLoaderRoute: typeof PortalShipmentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/support': {
      id: '/portal/support'
      path: '/support'
      fullPath: '/portal/support'
      preLoaderRoute: typeof PortalSupportRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tracking': {
      id: '/portal/tracking'
      path: '/tracking'
      fullPath: '/portal/tracking'
      preLoaderRoute: typeof PortalTrackingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/audit-logs': {
      id: '/staff/audit-logs'
      path: '/audit-logs'
      fullPath: '/staff/audit-logs'
      preLoaderRoute: typeof StaffAuditLogsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/company': {
      id: '/staff/company'
      path: '/company'
      fullPath: '/staff/company'
      preLoaderRoute: typeof StaffCompanyRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/customers': {
      id: '/staff/customers'
      path: '/customers'
      fullPath: '/staff/customers'
      preLoaderRoute: typeof StaffCustomersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/documents': {
      id: '/staff/documents'
      path: '/documents'
      fullPath: '/staff/documents'
      preLoaderRoute: typeof StaffDocumentsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/driver-payments': {
      id: '/staff/driver-payments'
      path: '/driver-payments'
      fullPath: '/staff/driver-payments'
      preLoaderRoute: typeof StaffDriverPaymentsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/drivers': {
      id: '/staff/drivers'
      path: '/drivers'
      fullPath: '/staff/drivers'
      preLoaderRoute: typeof StaffDriversRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/finance': {
      id: '/staff/finance'
      path: '/finance'
      fullPath: '/staff/finance'
      preLoaderRoute: typeof StaffFinanceRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/fleet': {
      id: '/staff/fleet'
      path: '/fleet'
      fullPath: '/staff/fleet'
      preLoaderRoute: typeof StaffFleetRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/fuel': {
      id: '/staff/fuel'
      path: '/fuel'
      fullPath: '/staff/fuel'
      preLoaderRoute: typeof StaffFuelRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/maintenance': {
      id: '/staff/maintenance'
      path: '/maintenance'
      fullPath: '/staff/maintenance'
      preLoaderRoute: typeof StaffMaintenanceRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/notifications': {
      id: '/staff/notifications'
      path: '/notifications'
      fullPath: '/staff/notifications'
      preLoaderRoute: typeof StaffNotificationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/reports': {
      id: '/staff/reports'
      path: '/reports'
      fullPath: '/staff/reports'
      preLoaderRoute: typeof StaffReportsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/salaries': {
      id: '/staff/salaries'
      path: '/salaries'
      fullPath: '/staff/salaries'
      preLoaderRoute: typeof StaffSalariesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/settings': {
      id: '/staff/settings'
      path: '/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof StaffSettingsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/shipments': {
      id: '/staff/shipments'
      path: '/shipments'
      fullPath: '/staff/shipments'
      preLoaderRoute: typeof StaffShipmentsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/transport-orders': {
      id: '/staff/transport-orders'
      path: '/transport-orders'
      fullPath: '/staff/transport-orders'
      preLoaderRoute: typeof StaffTransportOrdersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/trips': {
      id: '/staff/trips'
      path: '/trips'
      fullPath: '/staff/trips'
      preLoaderRoute: typeof StaffTripsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/users': {
      id: '/staff/users'
      path: '/users'
      fullPath: '/staff/users'
      preLoaderRoute: typeof StaffUsersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/vehicle-profit': {
      id: '/staff/vehicle-profit'
      path: '/vehicle-profit'
      fullPath: '/staff/vehicle-profit'
      preLoaderRoute: typeof StaffVehicleProfitRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/warehouses': {
      id: '/staff/warehouses'
      path: '/warehouses'
      fullPath: '/staff/warehouses'
      preLoaderRoute: typeof StaffWarehousesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/drivers/$driverId': {
      id: '/staff/drivers/$driverId'
      path: '/$driverId'
      fullPath: '/staff/drivers/$driverId'
      preLoaderRoute: typeof StaffDriversDriverIdRouteImport
      parentRoute: typeof StaffDriversRoute
    }
  }
}

interface DriverRouteChildren {
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface PortalRouteChildren {
  PortalInvoicesRoute: typeof PortalInvoicesRoute
  PortalNotificationsRoute: typeof PortalNotificationsRoute
  PortalPaymentsRoute: typeof PortalPaymentsRoute
  PortalPickupsRoute: typeof PortalPickupsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalShipmentsRoute: typeof PortalShipmentsRoute
  PortalSupportRoute: typeof PortalSupportRoute
  PortalTrackingRoute: typeof PortalTrackingRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalInvoicesRoute: PortalInvoicesRoute,
  PortalNotificationsRoute: PortalNotificationsRoute,
  PortalPaymentsRoute: PortalPaymentsRoute,
  PortalPickupsRoute: PortalPickupsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalShipmentsRoute: PortalShipmentsRoute,
  PortalSupportRoute: PortalSupportRoute,
  PortalTrackingRoute: PortalTrackingRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface StaffDriversRouteChildren {
  StaffDriversDriverIdRoute: typeof StaffDriversDriverIdRoute
}

const StaffDriversRouteChildren: StaffDriversRouteChildren = {
  StaffDriversDriverIdRoute: StaffDriversDriverIdRoute,
}

const StaffDriversRouteWithChildren = StaffDriversRoute._addFileChildren(
  StaffDriversRouteChildren,
)

interface StaffRouteChildren {
  StaffAuditLogsRoute: typeof StaffAuditLogsRoute
  StaffCompanyRoute: typeof StaffCompanyRoute
  StaffCustomersRoute: typeof StaffCustomersRoute
  StaffDocumentsRoute: typeof StaffDocumentsRoute
  StaffDriverPaymentsRoute: typeof StaffDriverPaymentsRoute
  StaffDriversRoute: typeof StaffDriversRouteWithChildren
  StaffFinanceRoute: typeof StaffFinanceRoute
  StaffFleetRoute: typeof StaffFleetRoute
  StaffFuelRoute: typeof StaffFuelRoute
  StaffMaintenanceRoute: typeof StaffMaintenanceRoute
  StaffNotificationsRoute: typeof StaffNotificationsRoute
  StaffReportsRoute: typeof StaffReportsRoute
  StaffSalariesRoute: typeof StaffSalariesRoute
  StaffSettingsRoute: typeof StaffSettingsRoute
  StaffShipmentsRoute: typeof StaffShipmentsRoute
  StaffTransportOrdersRoute: typeof StaffTransportOrdersRoute
  StaffTripsRoute: typeof StaffTripsRoute
  StaffUsersRoute: typeof StaffUsersRoute
  StaffVehicleProfitRoute: typeof StaffVehicleProfitRoute
  StaffWarehousesRoute: typeof StaffWarehousesRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAuditLogsRoute: StaffAuditLogsRoute,
  StaffCompanyRoute: StaffCompanyRoute,
  StaffCustomersRoute: StaffCustomersRoute,
  StaffDocumentsRoute: StaffDocumentsRoute,
  StaffDriverPaymentsRoute: StaffDriverPaymentsRoute,
  StaffDriversRoute: StaffDriversRouteWithChildren,
  StaffFinanceRoute: StaffFinanceRoute,
  StaffFleetRoute: StaffFleetRoute,
  StaffFuelRoute: StaffFuelRoute,
  StaffMaintenanceRoute: StaffMaintenanceRoute,
  StaffNotificationsRoute: StaffNotificationsRoute,
  StaffReportsRoute: StaffReportsRoute,
  StaffSalariesRoute: StaffSalariesRoute,
  StaffSettingsRoute: StaffSettingsRoute,
  StaffShipmentsRoute: StaffShipmentsRoute,
  StaffTransportOrdersRoute: StaffTransportOrdersRoute,
  StaffTripsRoute: StaffTripsRoute,
  StaffUsersRoute: StaffUsersRoute,
  StaffVehicleProfitRoute: StaffVehicleProfitRoute,
  StaffWarehousesRoute: StaffWarehousesRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BranchesRoute: BranchesRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CreatePasswordRoute: CreatePasswordRoute,
  DriverRoute: DriverRouteWithChildren,
  FleetRoute: FleetRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IndustriesRoute: IndustriesRoute,
  LockRoute: LockRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  NewsRoute: NewsRoute,
  OtpRoute: OtpRoute,
  PortalRoute: PortalRouteWithChildren,
  QuoteRoute: QuoteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  StaffRoute: StaffRouteWithChildren,
  StaffLoginRoute: StaffLoginRoute,
  TrackRoute: TrackRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
